### ISSUE TITLE
Pullrequests welcome?

### ISSUE THREAD

**Issue by KarlZeilhofer** [lied/osvac#2]
Hi, 
are pullrequests with further adapters welcome?
I'm wondering, why this project has no forks. 
Greets, Karl

**Comment by lied** [comment]
Hi, i'm not the original author of the document. :-) the osvac neo was started by some guy from a forum (woodworker). He came up with fusion 360 and the parameters for it.
So forks are allowed, but maybe look here for a more recent version first.

Thema 'osVAC (neo) link-Sammlung' https://www.woodworker.de/forum/threads/osvac-neo-link-sammlung.124906/

It's German, but guessing from your name should be fine ;-)

**Comment by lied** [comment]
@KarlZeilhofer  Hi, I've now created a new version of adapters, it's not very tested yet, but it keeps growing while I'm changing to this instead of OSVACNeo.

It simplifies the structure a lot, by only using one projects instead of importing from different projects.
PRs to this are very welcome :-)
https://github.com/lied/osvac/blob/main/VaCADapt%20v57.f3d
